//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLogs
    {
        public int ID_Log { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string Action_Type { get; set; }
        public string Table_Name { get; set; }
        public Nullable<int> Record_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Log_Date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
