//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID_Record { get; set; }
        public int ID_Training { get; set; }
        public int ID_Player { get; set; }
        public bool Is_Present { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
