//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Players = new HashSet<Players>();
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int ID_Group { get; set; }
        public string Group_Name { get; set; }
        public int ID_Level { get; set; }
        public int ID_Coach { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Levels Levels { get; set; }
        public virtual ICollection<Players> Players { get; set; }
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
