//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Levels
    {
        public Levels()
        {
            this.Groups = new HashSet<Groups>();
        }
    
        public int ID_Level { get; set; }
        public string Level_Name { get; set; }
    
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
