//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RusakovPingTrackEntities : DbContext
    {
        public RusakovPingTrackEntities()
            : base("name=RusakovPingTrackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attendance> Attendance { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Levels> Levels { get; set; }
        public DbSet<Players> Players { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Training_Types> Training_Types { get; set; }
        public DbSet<Trainings> Trainings { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
