//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public Players()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int ID_Player { get; set; }
        public string Full_Name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Phone { get; set; }
        public int ID_Group { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
    }
}
