//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public int ID_Subscription { get; set; }
        public int ID_Player { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
