//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public Trainings()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int ID_Training { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int ID_Group { get; set; }
        public int ID_Coach { get; set; }
        public int ID_Type { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Training_Types Training_Types { get; set; }
        public virtual Users Users { get; set; }
    }
}
