//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Types
    {
        public Training_Types()
        {
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int ID_Type { get; set; }
        public string Type_Name { get; set; }
    
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
