//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingTrack.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Groups = new HashSet<Groups>();
            this.Players = new HashSet<Players>();
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int ID_User { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int ID_Role { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created_At { get; set; }
        public string Full_Name { get; set; }
    
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual ICollection<Players> Players { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
